### ISSUE TITLE
Running the figma-export Pod deletes some of my files

### ISSUE THREAD

**Issue by KeiroMidori** [RedMadRobot/figma-export#102]
When I run figma export 1 of my scheme configuration files gets deleted and my build post-action scripts gets messed up (some \n characters are replaced by an actual line return)

I don't have time to dive in the code and find the exact lines that produces such issue but if that rings a bell please fix it :)

I run it for an iOS project and here's my figma-export.yaml file:

```
figma:
  lightFileId: mytoken

common:
  colors:
    nameValidateRegexp: '^[a-zA-Z0-9_ -]+$'
    useSingleFile: true
    darkModeSuffix: '_dark'
  icons:
    figmaFrameName: Colors
    nameValidateRegexp: '^(ic)_(\d\d)_([a-z0-9_]+)$'
  images:
    figmaFrameName: Illustrations
    nameValidateRegexp: '^(img)_([a-z0-9_]+)$'

ios:
  xcodeprojPath: "./myproject.xcodeproj"
  target: "myproject"
  xcassetsPath: "./MyProject/DesignStyleguide/Styleguide.xcassets"
  xcassetsInMainBundle: true

  colors:
    useColorAssets: true
    assetsFolder: Colors
    nameStyle: camelCase
    colorSwift: "./MyProject/UIColor+Styleguide.swift"
```

I omitted images/icons/typography because I only use it to export colors for now by running:

```lane :sync_colors do
  Dir.chdir("../") do
    sh "Pods/FigmaExport/Release/figma-export colors -i figma-export.yaml"
  end
end
```

Please let me know if I can fix that myself by updating the config file or if I am missing something because for now I can't integrate figma export in my CI pipeline because of this issue.

Thank you !
