### ISSUE TITLE
pbxproj and xcscheme files are always modified

### ISSUE THREAD

**Issue by agarcia-wish** [RedMadRobot/figma-export#135]
Assets are located in a swift package and this is the definition for the yml file:

```
ios:
  # Path to xcodeproj
  xcodeprojPath: "./MyProject.xcodeproj"
  # # Xcode Target containing resources and corresponding swift code
  target: "Test"
  # # Absolute or relative path to the Assets.xcassets directory
  xcassetsPath: "InternalPackages/UI/Resources/Icons.xcassets"
  # # Is Assets.xcassets located in the main bundle?
  xcassetsInMainBundle: false
  # # [optional] Is Assets.xcassets located in a swift package? Default value is false.
  xcassetsInSwiftPackage: true
  ```

When I run figma-export pbxproj and xcscheme files for my project are modified.
