### ISSUE TITLE
DecodingError "meta"

### ISSUE THREAD

**Issue by Frank1234** [RedMadRobot/figma-export#253]
On v0.38.2, I get this error when I fetch colors, from variables. 

> Error: keyNotFound(CodingKeys(stringValue: "meta", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"meta\", intValue: nil) (\"meta\").", underlyingError: nil))

With the attached config file. It seems like it expects a "meta" node at the top level of my config?

```
---
figma:
  # [required] Identifier of the file containing light color palette, icons and light images. To obtain a file id, open the file in the browser. The file id will be present in the URL after the word file (or design) and before the file name.
  lightFileId: 123

# [optional] Common export parameters
common:
  variablesColors:
    tokensFileId: 123
    tokensCollectionName: Base Color
    lightModeName: Base
    primitivesModeName: Base
    composePackageName: "com.redmadrobot.androidcomposeexample.ui.figmaexport"
  icons:
    # Name of the Figma's frame where icons components are located
    figmaFrameName: Icons

# [optional] Android export parameters
android:
[...]
```
