### ISSUE TITLE
Custom filenames pattern

### ISSUE THREAD

**Issue by osipxd** [RedMadRobot/figma-export#27]
It would be great to have the possibility to customize the filenames pattern.  
It can be done with capture group references. Something like:
```yml
common:
  icons:
    nameRegex: '^(\d\d) \\ ([A-Za-z0-9 ]+)$'
    filename: 'icon_$2_$1'
```
> `32 \ Profile` -> `icon_profile_32`
