### ISSUE TITLE
Add support for several xcassets and Figma frames

### ISSUE THREAD

**Issue by subdan** [RedMadRobot/figma-export#4]
Today extension has its own xcassets file. I would like to be able to specify a frame → xcassets pair (which frame to export to which xcassets).
Example:
```
ios:
  - xcassetsPath: "/Users/d.subbotin/app_name/Resources/Assets.xcassets"
    images:
      frameName: Illustrations
      assetsFolder: Illustrations
  - xcassetsPath: "/Users/d.subbotin/app_name/Widget/Resources/Assets.xcassets"
    images:
      frameName: Illustrations_widget
      assetsFolder: Illustrations
```
