### ISSUE TITLE
Template Image and Original Image for Xcode

### ISSUE THREAD

**Issue by greatmatis** [RedMadRobot/figma-export#54]
FigmaExport is great, we're using it now on a live project, everybody loves it ✨ 

One of our iOS developers asking: is it possible to export pdf's in "Original Image" render mode, not "Template Image"? If it's not, can it be a feature request? :)

**Comment by subdan** [comment]
Hi, Thanks.

It isn‘t possible to use "Original Image" render mode when exporting icons right now. I will add ability to set render mode in the config file.

```yaml
icons:
  format: pdf
  assetsFolder: Icons
  nameStyle: camelCase
  renderMode: original // optional, default value = "template"
```
