### ISSUE TITLE
Figma-export issue

### ISSUE THREAD

**Issue by Simon-developer** [RedMadRobot/figma-export#98]
Добрый день! 
Пытался воспользоваться вашим решением для автоматизации импорта ассетов
(в связке fastlane+cocoa) все застопорилось на этом моменте, не подскажете, чем это могло быть вызвано и какие возможные варианты решения? 
Заранее спасибо!

<img width="921" alt="Снимок экрана 2021-04-14 в 09 52 51" src="https://user-images.githubusercontent.com/61358874/114679649-a8144080-9d0c-11eb-8501-7aa27abe4dc5.png">

**Comment by subdan** [comment]
Добрый.
По какой-то непонятной причине FigmaExport не может отредактировать файл Xcode проекта. Чтобы исправить эту проблему мне нужно повторить её. У вас будет возможность дать мне доступ к вашему Figma файлу и (или) к Xcode проекту?

**Comment by subdan** [comment]
Возможно у вас неправильно настроен конфиг файл. Проверьте вот эти параметры:

```yml
ios:
  # Path to xcodeproj
  xcodeprojPath: "./Example.xcodeproj"

  # Xcode Target containing resources and corresponding swift code
  target: "UIComponents"

  # Absolute or relative path to the Assets.xcassets directory
  xcassetsPath: "./Resources/Assets.xcassets"

  # Is Assets.xcassets located in the main bundle?
  xcassetsInMainBundle: true
```
